#!/usr/bin/env bash
# Generates configuration only. Does not install packages, start containers,
# connect to providers, or touch storage devices.
set -euo pipefail
umask 077

project_dir="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)"
output="$project_dir/.env"
origin=''
secure=true

usage() {
  printf '%s\n' \
    'Usage: bash infrastructure/setup.sh --origin https://stream.example.com [--output PATH]' \
    '       bash infrastructure/setup.sh --local [--output PATH]' \
    'Existing files are never overwritten. --local enables HTTP on localhost:8088 only.'
}

while (($#)); do
  case "$1" in
    --origin)
      [[ $# -ge 2 && -z "$origin" ]] || { usage >&2; exit 1; }
      origin="$2"; shift 2 ;;
    --local)
      [[ -z "$origin" ]] || { usage >&2; exit 1; }
      origin='http://localhost:8088'; secure=false; shift ;;
    --output)
      [[ $# -ge 2 && -n "$2" ]] || { usage >&2; exit 1; }
      output="$2"; shift 2 ;;
    --help|-h) usage; exit 0 ;;
    *) usage >&2; exit 1 ;;
  esac
done

if [[ -z "$origin" ]]; then usage >&2; exit 1; fi
if [[ "$secure" == true ]]; then
  # Restrict input to a hostname and optional port; no dotenv/shell metacharacters.
  [[ "$origin" =~ ^https://[a-zA-Z0-9]([a-zA-Z0-9.-]*[a-zA-Z0-9])?(:[0-9]{1,5})?$ ]] || {
    printf '%s\n' 'Use an HTTPS origin with an ASCII hostname, no path or trailing slash.' >&2
    exit 1
  }
  authority="${origin#https://}"
  if [[ "$authority" == *:* ]]; then
    port="${authority##*:}"
    ((10#$port >= 1 && 10#$port <= 65535)) || { printf '%s\n' 'Invalid port.' >&2; exit 1; }
    # Url::origin normalizes the default HTTPS port away.
    if ((10#$port == 443)); then
      origin="https://${authority%:*}"
    else
      origin="https://${authority%:*}:$((10#$port))"
    fi
  fi
  origin="${origin,,}"
fi
[[ ! -e "$output" && ! -L "$output" ]] || {
  printf '%s\n' 'Configuration already exists; no changes made.' >&2
  exit 1
}
command -v openssl >/dev/null || { printf '%s\n' 'Install OpenSSL before running setup.' >&2; exit 1; }

# Generate everything before opening the output, and never echo secret values.
db_password="$(openssl rand -hex 32)"
admin_password="$(openssl rand -hex 32)"
engine_password="$(openssl rand -hex 32)"
obs_password="$(openssl rand -hex 32)"
encryption_key="$(openssl rand -base64 32)"
set -o noclobber
cat > "$output" <<EOF
# Generated by Signal setup. Keep private and back up ENCRYPTION_KEY.
POSTGRES_PASSWORD=$db_password
ADMIN_USER=admin
ADMIN_PASSWORD=$admin_password
MEDIAMTX_API_PASSWORD=$engine_password
OBS_PASSWORD=$obs_password
ENCRYPTION_KEY=$encryption_key
PUBLIC_ORIGIN=$origin
COOKIE_SECURE=$secure
DASHBOARD_BIND=127.0.0.1
DASHBOARD_PORT=8088
INGEST_BIND=0.0.0.0
DATA_PATH=/data
MEDIAMTX_API_URL=http://mediamtx:9997
MEDIAMTX_RTSP_URL=rtsp://mediamtx:8554/live
FILE_BROWSER_URL=http://192.168.1.7:8080
YOUTUBE_STREAM_KEY=
YOUTUBE_RTMP_URL=rtmps://a.rtmp.youtube.com/live2
FACEBOOK_STREAM_KEY=
FACEBOOK_RTMP_URL=rtmps://live-api-s.facebook.com:443/rtmp
EOF
printf '%s\n' 'Configuration created with private file permissions. No services were started.' \
  'Read ADMIN_PASSWORD privately from the generated file when signing in.' \
  'Next: python3 infrastructure/preflight.py'
